"""Shared constants for configuration and environment access."""

from __future__ import annotations

GOOGLE_CLOUD_PROJECT_ENV_VAR: str = "GOOGLE_CLOUD_PROJECT"
GOOGLE_APPLICATION_CREDENTIALS_ENV_VAR: str = "GOOGLE_APPLICATION_CREDENTIALS"
ANTHROPIC_API_KEY_SECRET_NAME: str = "API_KEY_ANTHROPIC"

__all__ = [
    "GOOGLE_CLOUD_PROJECT_ENV_VAR",
    "GOOGLE_APPLICATION_CREDENTIALS_ENV_VAR",
    "ANTHROPIC_API_KEY_SECRET_NAME",
]
