"""Shared constants for configuration and environment access."""

from __future__ import annotations

GOOGLE_CLOUD_PROJECT_ENV_VAR: str = "GOOGLE_CLOUD_PROJECT"
GOOGLE_APPLICATION_CREDENTIALS_ENV_VAR: str = "GOOGLE_APPLICATION_CREDENTIALS"

# API keys
ANTHROPIC_API_KEY_SECRET_NAME: str = "API_KEY_ANTHROPIC"
GOOGLE_GEMINI_API_KEY_SECRET_NAME: str = "API_KEY_GEMINI"
MISTRAL_API_KEY_SECRET_NAME: str = "API_KEY_MISTRAL"
OPENAI_API_KEY_SECRET_NAME: str = "API_KEY_OPENAI"
XAI_API_KEY_SECRET_NAME: str = "API_KEY_XAI"
TOGETHER_API_KEY_SECRET_NAME: str = "API_KEY_TOGETHERAI"

__all__ = [
    "GOOGLE_CLOUD_PROJECT_ENV_VAR",
    "GOOGLE_APPLICATION_CREDENTIALS_ENV_VAR",
    "ANTHROPIC_API_KEY_SECRET_NAME",
    "GOOGLE_GEMINI_API_KEY_SECRET_NAME",
    "MISTRAL_API_KEY_SECRET_NAME",
    "OPENAI_API_KEY_SECRET_NAME",
    "XAI_API_KEY_SECRET_NAME",
    "TOGETHER_API_KEY_SECRET_NAME",
]
